import { FormConfig } from "@/types/employer/job";

export const FORM_TEMPLATES: FormConfig[] = [
  {
    id: "basic",
    name: "Basic Contact Form",
    fields: [
      {
        id: "name",
        type: "text",
        label: "Full Name",
        placeholder: "John Doe",
        required: true,
        semanticType: "name",
        importance: "critical",
      },
      {
        id: "email",
        type: "text",
        label: "Email Address",
        placeholder: "john.doe@example.com",
        required: true,
        semanticType: "email",
        importance: "critical",
      },
      {
        id: "resume",
        type: "file",
        label: "Resume",
        required: true,
        semanticType: "resume",
        importance: "critical",
      },
      {
        id: "phone",
        type: "text",
        label: "Phone Number",
        placeholder: "+1 (555) 000-0000",
        required: true,
        semanticType: "phone",
        importance: "required",
      },
      {
        id: "location",
        type: "text",
        label: "Current Location",
        placeholder: "San Francisco, CA",
        required: true,
        semanticType: "location",
        importance: "required",
      },
      {
        id: "experience",
        type: "number",
        label: "Years of Professional Experience",
        placeholder: "e.g., 5",
        required: true,
        semanticType: "experience_years",
        importance: "required",
      },
      {
        id: "education",
        type: "paragraph",
        label: "Education",
        placeholder: "e.g., BS in Computer Science — MIT (2020–2024)",
        required: false,
        semanticType: "education",
        importance: "nice-to-have",
      },
    ],
  },
  {
    id: "engineering",
    name: "Technical Engineering Intake",
    fields: [
      {
        id: "name",
        type: "text",
        label: "Full Name",
        placeholder: "John Doe",
        required: true,
        semanticType: "name",
        importance: "critical",
      },
      {
        id: "email",
        type: "text",
        label: "Email Address",
        placeholder: "john.doe@example.com",
        required: true,
        semanticType: "email",
        importance: "critical",
      },
      {
        id: "resume",
        type: "file",
        label: "Resume",
        required: true,
        semanticType: "resume",
        importance: "critical",
      },
      {
        id: "phone",
        type: "text",
        label: "Phone Number",
        placeholder: "+1 (555) 000-0000",
        required: true,
        semanticType: "phone",
        importance: "required",
      },
      {
        id: "location",
        type: "text",
        label: "Current Location",
        placeholder: "San Francisco, CA",
        required: true,
        semanticType: "location",
        importance: "required",
      },
      {
        id: "experience",
        type: "number",
        label: "Years of Professional Software Experience",
        placeholder: "e.g., 5",
        required: true,
        semanticType: "experience_years",
        importance: "required",
        expectedAnswer: 3, // Expected at least 3 years
      },
      {
        id: "education",
        type: "paragraph",
        label: "Education",
        placeholder: "e.g., BS in Computer Science — MIT (2020–2024)",
        required: false,
        semanticType: "education",
        importance: "nice-to-have",
      },
      {
        id: "skills",
        type: "text",
        label: "Key Skills (comma separated)",
        placeholder: "React, TypeScript, Node.js",
        required: true,
        semanticType: "skills",
        importance: "required",
      },
      {
        id: "github",
        type: "text",
        label: "GitHub Profile URL",
        placeholder: "https://github.com/username",
        required: false,
        semanticType: "github",
        importance: "nice-to-have",
      },
      {
        id: "linkedin",
        type: "text",
        label: "LinkedIn Profile URL",
        placeholder: "https://linkedin.com/in/username",
        required: false,
        semanticType: "linkedin",
        importance: "nice-to-have",
      },
    ],
  },
  {
    id: "design",
    name: "Creative & Design Intake",
    fields: [
      {
        id: "name",
        type: "text",
        label: "Full Name",
        placeholder: "John Doe",
        required: true,
        semanticType: "name",
        importance: "critical",
      },
      {
        id: "email",
        type: "text",
        label: "Email Address",
        placeholder: "john.doe@example.com",
        required: true,
        semanticType: "email",
        importance: "critical",
      },
      {
        id: "resume",
        type: "file",
        label: "Resume / CV",
        required: true,
        semanticType: "resume",
        importance: "critical",
      },
      {
        id: "phone",
        type: "text",
        label: "Phone Number",
        placeholder: "+1 (555) 000-0000",
        required: true,
        semanticType: "phone",
        importance: "required",
      },
      {
        id: "location",
        type: "text",
        label: "Current Location",
        placeholder: "San Francisco, CA",
        required: true,
        semanticType: "location",
        importance: "required",
      },
      {
        id: "experience",
        type: "number",
        label: "Years of Professional Experience",
        placeholder: "e.g., 5",
        required: true,
        semanticType: "experience_years",
        importance: "required",
      },
      {
        id: "education",
        type: "paragraph",
        label: "Education",
        placeholder: "e.g., BS in Computer Science — MIT (2020–2024)",
        required: false,
        semanticType: "education",
        importance: "nice-to-have",
      },
      {
        id: "portfolio",
        type: "text",
        label: "Portfolio Link",
        placeholder: "https://myportfolio.com",
        required: true,
        semanticType: "portfolio",
        importance: "critical",
      },
      {
        id: "tools",
        type: "multi-select",
        label: "Design Tools you are expert in",
        required: true,
        options: ["Figma", "Adobe Photoshop", "Adobe Illustrator", "Sketch", "Framer", "Principle"],
        semanticType: "skills",
        importance: "required",
      },
      {
        id: "linkedin",
        type: "text",
        label: "LinkedIn Profile URL",
        placeholder: "https://linkedin.com/in/username",
        required: false,
        semanticType: "linkedin",
        importance: "nice-to-have",
      },
    ],
  },
  {
    id: "comprehensive",
    name: "Comprehensive Questionnaire",
    fields: [
      {
        id: "name",
        type: "text",
        label: "Full Name",
        placeholder: "John Doe",
        required: true,
        semanticType: "name",
        importance: "critical",
      },
      {
        id: "email",
        type: "text",
        label: "Email Address",
        placeholder: "john.doe@example.com",
        required: true,
        semanticType: "email",
        importance: "critical",
      },
      {
        id: "phone",
        type: "text",
        label: "Phone Number",
        placeholder: "+1 (555) 000-0000",
        required: true,
        semanticType: "phone",
        importance: "required",
      },
      {
        id: "location",
        type: "text",
        label: "Current Location",
        placeholder: "San Francisco, CA",
        required: true,
        semanticType: "location",
        importance: "required",
      },
      {
        id: "resume",
        type: "file",
        label: "Resume / CV File",
        required: true,
        semanticType: "resume",
        importance: "critical",
      },
      {
        id: "experience",
        type: "number",
        label: "Years of Professional Experience",
        placeholder: "e.g., 5",
        required: true,
        semanticType: "experience_years",
        importance: "required",
      },
      {
        id: "education",
        type: "paragraph",
        label: "Education",
        placeholder: "e.g., BS in Computer Science — MIT (2020–2024)",
        required: false,
        semanticType: "education",
        importance: "nice-to-have",
      },
      {
        id: "linkedin",
        type: "text",
        label: "LinkedIn Profile",
        placeholder: "https://linkedin.com/in/username",
        required: false,
        semanticType: "linkedin",
        importance: "nice-to-have",
      },
      {
        id: "cover_letter",
        type: "paragraph",
        label: "Cover Letter",
        placeholder: "Describe why you are a great fit...",
        required: false,
        semanticType: "cover_letter",
        importance: "nice-to-have",
      },
      {
        id: "sponsorship",
        type: "radio",
        label: "Will you require visa sponsorship to work in this location?",
        required: true,
        options: ["Yes", "No"],
        semanticType: "custom",
        importance: "required",
      },
    ],
  },
];
