alter extension citext set schema extensions;
drop policy "Anyone can view employer assets" on storage.objects;
drop policy "Anyone can view talent assets" on storage.objects;
drop policy "Users can view own profile." on public.profiles;
drop policy "Users can update own profile." on public.profiles;
create index companies_owner_user_idx on public.companies(owner_user_id);
create index companies_verified_by_idx on public.companies(verified_by) where verified_by is not null;
create index company_memberships_user_idx on public.company_memberships(user_id);
create index company_memberships_invited_by_idx on public.company_memberships(invited_by) where invited_by is not null;
create index company_memberships_approved_by_idx on public.company_memberships(approved_by) where approved_by is not null;
create index company_member_permissions_updated_by_idx on public.company_member_permissions(updated_by) where updated_by is not null;
create index company_affiliation_requests_requester_idx on public.company_affiliation_requests(requester_user_id);
create index company_affiliation_requests_decided_by_idx on public.company_affiliation_requests(decided_by) where decided_by is not null;
create index company_invitations_invited_by_idx on public.company_invitations(invited_by);
create index company_invitations_accepted_by_idx on public.company_invitations(accepted_by) where accepted_by is not null;
create index company_verification_requests_company_idx on public.company_verification_requests(company_id);
create index company_verification_requests_submitted_by_idx on public.company_verification_requests(submitted_by);
create index company_verification_requests_reviewed_by_idx on public.company_verification_requests(reviewed_by) where reviewed_by is not null;
create index employer_talent_blacklist_acted_by_idx on public.employer_talent_blacklist(acted_by_user_id) where acted_by_user_id is not null;
create index talent_experience_verifications_reviewer_idx on public.talent_experience_verifications(reviewer_user_id) where reviewer_user_id is not null;
notify pgrst, 'reload schema';
