create table public.company_affiliation_requests (
  id uuid primary key default gen_random_uuid(),
  requester_user_id uuid not null references auth.users(id) on delete cascade,
  company_id uuid references public.companies(id) on delete cascade,
  target_email_hash text not null,
  target_email_masked text not null,
  status public.company_request_status not null default 'pending',
  decided_by uuid references auth.users(id) on delete set null,
  decision_note text,
  decided_at timestamptz,
  expires_at timestamptz not null default (now() + interval '30 days'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index company_affiliation_requests_one_pending on public.company_affiliation_requests(requester_user_id) where status = 'pending';
create index company_affiliation_requests_company_status_idx on public.company_affiliation_requests(company_id, status, created_at desc);

create table public.company_invitations (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  email citext not null,
  role public.company_member_role not null default 'recruiter',
  token_hash text not null unique,
  invited_by uuid not null references auth.users(id) on delete cascade,
  status public.company_request_status not null default 'pending',
  provider_message_id text,
  delivery_error text,
  expires_at timestamptz not null default (now() + interval '7 days'),
  accepted_by uuid references auth.users(id) on delete set null,
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index company_invitations_one_pending_email on public.company_invitations(company_id, email) where status = 'pending';
create index company_invitations_company_status_idx on public.company_invitations(company_id, status, created_at desc);

create table public.company_audit_events (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index company_audit_events_company_created_idx on public.company_audit_events(company_id, created_at desc);
create index company_audit_events_actor_created_idx on public.company_audit_events(actor_user_id, created_at desc);

create table public.company_verification_requests (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  submitted_by uuid not null references auth.users(id) on delete cascade,
  legal_name text not null,
  website text not null,
  business_email citext not null,
  evidence_paths text[] not null default '{}',
  notes text,
  status public.company_verification_status not null default 'pending',
  reviewed_by uuid references auth.users(id) on delete set null,
  decision_note text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index company_verification_one_pending on public.company_verification_requests(company_id) where status = 'pending';
create index company_verification_requests_status_created_idx on public.company_verification_requests(status, created_at);

create table public.platform_staff (
  user_id uuid primary key references auth.users(id) on delete cascade,
  can_review_companies boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.conversation_read_states (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  last_read_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);
create index conversation_read_states_user_read_idx on public.conversation_read_states(user_id, last_read_at desc);

alter table public.company_affiliation_requests enable row level security;
alter table public.company_invitations enable row level security;
alter table public.company_audit_events enable row level security;
alter table public.company_verification_requests enable row level security;
alter table public.platform_staff enable row level security;
alter table public.conversation_read_states enable row level security;
